#!/bin/bash
sudo apt install -y \
autoconf \
autoconf-archive \
autogen \
automake \
autotools-dev \
bison \
bsdutils \
build-essential \
certbot \
clang \
cmake \
cmake-data \
cpulimit \
debian-goodies \
doxygen \
extra-cmake-modules \
g++ \
glances \
golang \
imagemagick \
libaio-dev \
libaom-dev \
libargon2-dev \
libatomic-ops-dev \
libbison-dev \
libboost-all-dev \
libbpfcc-dev \
libbrotli-dev \
libbsd-dev \
libbz2-dev \
libcurl4-openssl-dev \
libelf-dev \
libfreetype6-dev \
libgd-dev \
libgd-ocaml-dev \
libgeoip-dev \
libgeoip-dev \
libgflags-dev \
libgif-dev \
libgoogle-perftools-dev \
libheif-dev \
libipmimonitoring-dev \
libjemalloc-dev \
libjpeg-dev \
libjson-c-dev \
liblz4-dev \
libmnl-dev \
libncurses-dev \
libnetfilter-acct-dev \
libonig-dev \
libopenexr-dev \
libpcre3-dev \
libperl-dev \
libpng-dev \
libprotobuf-dev \
libreadline-dev \
librtmp-dev \
libsnappy-dev \
libsodium-dev \
libsqlite3-dev \
libssl-dev \
libtirpc-dev \
libtool \
libunwind-dev \
libuv1-dev \
libvips-dev \
libwebp-dev \
libwebsockets-dev \
libxslt1-dev \
libyajl-dev \
libzip-dev \
linux-tools-common \
linux-tools-generic \
locales-all \
mailutils \
make \
moreutils \
multitail \
nasm \
ncdu \
net-tools \
ninja-build \
num-utils \
p7zip-full \
pigz \
pkg-config \
re2c \
redis \
ruby-full \
sqlite3 \
subversion \
tree \
unzip \
uuid-dev \
virtualenv \
yasm \
zip \
zlib1g-dev \
zsh \
&& sudo apt -y clean \
&& sudo apt -y autoclean \
&& sudo apt -y autoremove --purge
&& echo 'Done.'
